{"uuid": "ab647338-6f0b-47ad-85fe-3a9af6006859", "children": ["3d7cb190-d66d-4e0f-9ea6-96a2a4f809ff"], "befores": [{"name": "login_precondition", "status": "broken", "statusDetails": {"message": "AttributeError: 'ConfigReader' object has no attribute 'get_user_credentials'\n", "trace": "  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/tests/test_checkout.py\", line 20, in login_precondition\n    user_creds = self.config.get_user_credentials(\"standard_user\")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1753588149223, "stop": 1753588149223}], "start": 1753588149223, "stop": 1753588149249}