{"uuid": "95839fd3-c384-4522-bd1c-7ebb99f46660", "children": ["6a9ebd0f-6837-43d1-9814-97ff40dd239f"], "befores": [{"name": "login_precondition", "status": "broken", "statusDetails": {"message": "AttributeError: 'ConfigReader' object has no attribute 'get_user_credentials'\n", "trace": "  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/tests/test_checkout.py\", line 20, in login_precondition\n    user_creds = self.config.get_user_credentials(\"standard_user\")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1753552174074, "stop": 1753552174074}], "start": 1753552174074, "stop": 1753552174095}