{"name": "test_login_valid", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed: Not on dashboard page.\nassert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x102834b20>()\n +    where <built-in method lower of str object at 0x102834b20> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f3d9b046c27fc1927443da56a25c4407\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f3d9b046c27fc1927443da56a25c4407\")> = <tests.login_test.TestLoginWeb object at 0x1026a7110>.driver", "trace": "self = <tests.login_test.TestLoginWeb object at 0x1026a7110>\n\n    @allure.story(\"Valid Login\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login_valid(self):\n        login_pg = LoginPage(self.driver)\n        login_pg.do_login(ConfigReader.get_username(), ConfigReader.get_password())\n        sleep(3)\n>       assert \"dashboard\" in self.driver.current_url.lower(), \"Login failed: Not on dashboard page.\"\nE       AssertionError: Login failed: Not on dashboard page.\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x102834b20>()\nE        +    where <built-in method lower of str object at 0x102834b20> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f3d9b046c27fc1927443da56a25c4407\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f3d9b046c27fc1927443da56a25c4407\")> = <tests.login_test.TestLoginWeb object at 0x1026a7110>.driver\n\ntests/login_test.py:16: AssertionError"}, "attachments": [{"name": "Lá»—i: test_login_valid_failure.png", "source": "20d81445-7190-493c-8ea6-109f903a13e0-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "9c133edb-492f-4034-8267-79c2c53f74f6-attachment.txt", "type": "text/plain"}], "start": 1753022946402, "stop": 1753022949597, "uuid": "282bfc7a-e611-407b-a435-2e9344ea2978", "historyId": "3668f0babf23e581b9c79ac10463fa1b", "testCaseId": "3668f0babf23e581b9c79ac10463fa1b", "fullName": "tests.login_test.TestLoginWeb#test_login_valid", "labels": [{"name": "story", "value": "Valid Login"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLoginWeb"}, {"name": "host", "value": "DUCs-MacBook-Air.local"}, {"name": "thread", "value": "53237-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}