{"name": "test_login_valid", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed: Not on dashboard page.\nassert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x105380490>()\n +    where <built-in method lower of str object at 0x105380490> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"12ffe804b25f3a9c50f2a6b8e2018eec\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"12ffe804b25f3a9c50f2a6b8e2018eec\")> = <tests.login_test.TestLoginWeb object at 0x1051e3110>.driver", "trace": "self = <tests.login_test.TestLoginWeb object at 0x1051e3110>\n\n    @allure.story(\"Valid Login\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login_valid(self):\n        login_pg = LoginPage(self.driver)\n        login_pg.do_login(ConfigReader.get_username(), ConfigReader.get_password())\n        sleep(3)\n>       assert \"dashboard\" in self.driver.current_url.lower(), \"Login failed: Not on dashboard page.\"\nE       AssertionError: Login failed: Not on dashboard page.\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x105380490>()\nE        +    where <built-in method lower of str object at 0x105380490> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"12ffe804b25f3a9c50f2a6b8e2018eec\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"12ffe804b25f3a9c50f2a6b8e2018eec\")> = <tests.login_test.TestLoginWeb object at 0x1051e3110>.driver\n\ntests/login_test.py:16: AssertionError"}, "attachments": [{"name": "Lá»—i: test_login_valid_failure.png", "source": "d63da854-5940-4ebd-be5e-89e76e298e54-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "b9ec34f8-62b5-4ac0-9a1e-9256341795e3-attachment.txt", "type": "text/plain"}], "start": 1753025953014, "stop": 1753025956984, "uuid": "223368cc-6f9d-4055-82e3-28cc8ab065cc", "historyId": "3668f0babf23e581b9c79ac10463fa1b", "testCaseId": "3668f0babf23e581b9c79ac10463fa1b", "fullName": "tests.login_test.TestLoginWeb#test_login_valid", "labels": [{"name": "story", "value": "Valid Login"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLoginWeb"}, {"name": "host", "value": "DUCs-MacBook-Air.local"}, {"name": "thread", "value": "54167-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}