{"name": "test_login_valid", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed: Not on dashboard page.\nassert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x1047dc420>()\n +    where <built-in method lower of str object at 0x1047dc420> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bc6b2d690b433ed1eb9b81bacf230f36\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bc6b2d690b433ed1eb9b81bacf230f36\")> = <tests.login_test.TestLoginWeb object at 0x10461f110>.driver", "trace": "self = <tests.login_test.TestLoginWeb object at 0x10461f110>\n\n    @allure.story(\"Valid Login\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login_valid(self):\n        login_pg = LoginPage(self.driver)\n        login_pg.do_login(ConfigReader.get_username(), ConfigReader.get_password())\n        sleep(3)\n>       assert \"dashboard\" in self.driver.current_url.lower(), \"Login failed: Not on dashboard page.\"\nE       AssertionError: Login failed: Not on dashboard page.\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x1047dc420>()\nE        +    where <built-in method lower of str object at 0x1047dc420> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bc6b2d690b433ed1eb9b81bacf230f36\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bc6b2d690b433ed1eb9b81bacf230f36\")> = <tests.login_test.TestLoginWeb object at 0x10461f110>.driver\n\ntests/login_test.py:16: AssertionError"}, "attachments": [{"name": "Lá»—i: test_login_valid_failure.png", "source": "9c3dca45-42c9-488d-bf55-f52366ea189b-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "8532335b-6440-44c5-b843-519de2d8767d-attachment.txt", "type": "text/plain"}], "start": 1753025161702, "stop": 1753025165679, "uuid": "d420dcfa-8a7c-4601-bffe-8cfa978ad73d", "historyId": "3668f0babf23e581b9c79ac10463fa1b", "testCaseId": "3668f0babf23e581b9c79ac10463fa1b", "fullName": "tests.login_test.TestLoginWeb#test_login_valid", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "Valid Login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLoginWeb"}, {"name": "host", "value": "DUCs-MacBook-Air.local"}, {"name": "thread", "value": "53847-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}